### ISSUE TITLE
Bad formatting: The data seems to be duplicated

### ISSUE THREAD

**Issue by tofarias** [oligus/jad#26]
### Description
I have 3 languages: english, portuguese and spanish.
In "Postman" when I call "/languages" in "preview" seems correct, but when I change to "Pretty" show me a "syntax error". I paste the response in JsonLint and the data seems to be duplicade.

The database:

![captura de tela em 2017-12-21 09-21-29](https://user-images.githubusercontent.com/7261216/34253834-60aa3330-e630-11e7-8506-c2e8f2eff825.png)

![captura de tela em 2017-12-21 09-06-11](https://user-images.githubusercontent.com/7261216/34253529-27247126-e62f-11e7-938e-4331b4fbf9d9.png)

![captura de tela em 2017-12-21 09-06-29](https://user-images.githubusercontent.com/7261216/34253582-5cb74db8-e62f-11e7-8c72-60c73cbbe794.png)

The "LanguageController":

![captura de tela em 2017-12-21 09-07-27](https://user-images.githubusercontent.com/7261216/34253776-2e6a2c68-e630-11e7-988b-90a2f5d396c4.png)

This is the response:

```json
{"data":[{"id":"1","type":"languages","attributes":{"name":"Portugu\u00eas","alias":"br","active":true,"deleted-at":null,"created-at":"2017-12-20 14:51:32","updated-at":"2017-12-20 14:51:32"}},{"id":"2","type":"languages","attributes":{"name":"Espanhol","alias":"es","active":true,"deleted-at":null,"created-at":"2017-12-20 14:51:33","updated-at":"2017-12-20 14:51:33"}},{"id":"3","type":"languages","attributes":{"name":"Ingl\u00eas","alias":"en","active":true,"deleted-at":null,"created-at":"2017-12-20 14:51:33","updated-at":"2017-12-20 14:51:33"}}],"links":{"self":"http:\/\/localhost\/languages"}}{"data":[{"id":"1","type":"languages","attributes":{"name":"Portugu\u00eas","alias":"br","active":true,"deleted-at":null,"created-at":"2017-12-20 14:51:32","updated-at":"2017-12-20 14:51:32"}},{"id":"2","type":"languages","attributes":{"name":"Espanhol","alias":"es","active":true,"deleted-at":null,"created-at":"2017-12-20 14:51:33","updated-at":"2017-12-20 14:51:33"}},{"id":"3","type":"languages","attributes":{"name":"Ingl\u00eas","alias":"en","active":true,"deleted-at":null,"created-at":"2017-12-20 14:51:33","updated-at":"2017-12-20 14:51:33"}}],"links":{"self":"http:\/\/localhost\/languages"}}
```

[Description of the bug or feature]

![captura de tela em 2017-12-21 09-09-58](https://user-images.githubusercontent.com/7261216/34253484-ea9eb496-e62e-11e7-9c88-bf86c28c953a.png)

**Comment by tofarias** [comment]
I made a mistake. The problem was a middleware that I has implemented. Sorry for this.

**Comment by oligus** [comment]
No problem at all! Thank you for using JAD, all questions, comments, requests are very welcome indeed :-)

Thanks for sharing!
