### ISSUE TITLE
The annotation "@Jad\Map\Annotations\Header" in class ... does not exist

### ISSUE THREAD

**Issue by tofarias** [oligus/jad#27]
### Description
![captura de tela em 2017-12-22 08-31-33](https://user-images.githubusercontent.com/7261216/34295082-8ed4d842-e6f2-11e7-9245-1d633d8f33db.png)

[Description of the bug or feature]

![captura de tela em 2017-12-22 08-34-19](https://user-images.githubusercontent.com/7261216/34295165-f6adbab0-e6f2-11e7-9a24-4e2ce335af5b.png)

![captura de tela em 2017-12-22 08-02-53](https://user-images.githubusercontent.com/7261216/34295015-488f9bd8-e6f2-11e7-913c-85042a749278.png)

**Comment by tofarias** [comment]
I made this: Doctrine\Common\Annotations\AnnotationRegistry::loadAnnotationClass(Rz2\TreinaFacil\Entities\Locale\Language::class); and not work.

**Comment by oligus** [comment]
In what context do you get this error, it looks as if you are running from the console directly?

https://github.com/oligus/jad/blob/master/docs/mapping.md might help, you might need to add:
`AnnotationRegistry::registerLoader('class_exists');`

**Comment by tofarias** [comment]
Ok, works nice with AnnotationRegistry::registerLoader('class_exists');
I put this in Lumen:: bootstrap/app.php

Thanks.

**Comment by oligus** [comment]
Ok cool, unfortunately that method is deprecated so we might want to go for another solution, but as long as it works I guess we are good.
