### ISSUE TITLE
Visibility @JAD\Attribute(visible=false)

### ISSUE THREAD

**Issue by tofarias** [oligus/jad#31]
### Description
Hi. 
![captura de tela em 2018-01-09 08-19-09](https://user-images.githubusercontent.com/7261216/34716042-d21bf7ee-f515-11e7-851a-8f60ef93afbf.png)

[Description of the bug or feature]

When I set the annotation @JAD\Attribute(visible=false) the field is still displayed on return.

![captura de tela em 2018-01-09 08-22-04](https://user-images.githubusercontent.com/7261216/34716169-31e263ac-f516-11e7-9e80-baa456f0964f.png)

**Comment by oligus** [comment]
Hi, thank you for the bug report!

Unfortunately, I cannot replicate this behaviour, at least not with my data set.

The routine for this is at src/Serializers/AbstractSerializer.php:113

There might be a a case where it misses but I cannot replicate it from where I stand, perhaps you have an idea?

**Comment by oligus** [comment]
ping @tofarias How is it going with this, did you figure out why it didn't hide the email property?

**Comment by tofarias** [comment]
Not yet. I'm actually using your package on Lumen Framework, but I have still other problems like a response codes.

The Header show "200"

![captura de tela em 2018-01-15 09-31-28](https://user-images.githubusercontent.com/7261216/34940509-e558413a-f9d6-11e7-897e-2c8be0154a1b.png)

**Comment by oligus** [comment]
Ok thanks, I will look into it. I have on the agenda to make a middleware for Lumen actually, I have started on it but it wont be ready for a while but I can post my progress here.

What does your middleware look like by the way?

**Comment by oligus** [comment]
Hi @tofarias, I have recently added a middleware for Lumen, somewhat untested I'm afraid but it works for the normal cases, you can check it out with version "dev-master" in composer if you would like to try it out, see https://github.com/oligus/jad#support to set it up.

I'm still curious about the visible bug, do you have an example on how to reproduce that bug?

thanks!

**Comment by tofarias** [comment]
Hi @oligus. 
for now I'm on another project.
