### ISSUE TITLE
Filter Relations

### ISSUE THREAD

**Issue by tofarias** [oligus/jad#38]
### Description

```
{{url}}:8000/api/jad/tracks?filter[tracks.albums][and][title][like]=taste
```

Above. Why is necessary filter[tracks.albums] instead of filter[albums]? I think everything is about Tracks entity.

[Description of the bug or feature]

**Comment by oligus** [comment]
That has to do with the way the filter is designed. You are welcome with a PR with improvements!

**Comment by tofarias** [comment]
Ok. thanks.
